[tox]
envlist = py{39,314}-driver-{sqliteXerial, hsqldb, mock, postgres, mysql, mssql, trino, oracle, db2, drill}

[gh-actions]
python =
  3.9: py39-driver-{hsqldb, sqliteXerial, mock, postgres, mysql}
  3.14: py314-driver-{hsqldb, sqliteXerial, mock, postgres, mysql}

[testenv]
usedevelop=True
passenv = JY_*,JAVA_HOME,JAVA8_DRIVERS
allowlist_externals = mvn, mkdir, bash
setenv =
  CLASSPATH = {tox_root}/test/jars/*:{tox_root}/test/mock-jars/*
  driver-mock: TESTNAME=test/test_mock.py test/test_infrastructure.py test/test_sqlalchemy.py
  driver-hsqldb: TESTNAME=test/test_hsqldb.py
  driver-sqliteXerial: TESTNAME=test/test_sqlite.py::SqliteXerialTest
  driver-sqlitePy: TESTNAME=test/test_sqlite.py::SqlitePyTest
  driver-postgres: TESTNAME=test/test_postgres.py
  driver-mysql: TESTNAME=test/test_mysql.py
  driver-mssql: TESTNAME=test/test_mssql.py
  driver-trino: TESTNAME=test/test_trino.py
  driver-oracle: TESTNAME=test/test_oracle.py
  driver-db2: TESTNAME=test/test_db2.py
  driver-drill: TESTNAME=test/test_drill.py
deps =
  JPype1>=1.0.0
  pyarrow>=16.0.0
  numpy
  pytest>=8.4.2
  pytest-xdist>=3.8.0
  SQLAlchemy>=2.0.0
  jaydebeapi>=1.2.3
commands =
  python --version
  bash test/build.sh
  bash test/download_jdbc_drivers.sh {env:JAVA8_DRIVERS:}
  driver-mock: mvn compile assembly:single -f mockdriver/pom.xml
  driver-mock: bash -c 'cp {tox_root}/mockdriver/target/mockdriver*.jar {tox_root}/test/mock-jars/'
  pytest {env:TESTNAME} -o "addopts=" --junitxml=build/test-reports/test-results-{envname}.xml -v
