[tox]
envlist = py{39,311}-driver-{sqliteXerial, hsqldb, mock, postgres, mysql, mssql, trino, oracle, db2, drill}

[gh-actions]
python =
  3.9: py39-driver-{hsqldb, sqliteXerial, mock, postgres, mysql, mssql, trino, oracle, db2, drill}
  3.11: py311-driver-{hsqldb, sqliteXerial, mock, postgres, mysql, mssql, trino, oracle, db2, drill}

[testenv]
# usedevelop required to enable coveralls source code view.
usedevelop=True
passenv = JY_*
allowlist_externals = mvn, mkdir, bash
setenv =
  CLASSPATH = {envdir}/javalib/*
  driver-mock: TESTNAME=test_mock
  driver-hsqldb: TESTNAME=test_integration.HsqldbTest test_integration.PropertiesDriverArgsPassingTest
  driver-sqliteXerial: TESTNAME=test_integration.SqliteXerialTest
  driver-sqlitePy: TESTNAME=test_integration.SqlitePyTest
  driver-postgres: TESTNAME=test_integration.PostgresTest
  driver-mysql: TESTNAME=test_integration.MySQLTest
  driver-mssql: TESTNAME=test_integration.MSSQLTest
  driver-trino: TESTNAME=test_integration.TrinoTest
  driver-oracle: TESTNAME=test_integration.OracleTest
  driver-db2: TESTNAME=test_integration.DB2Test
  driver-drill: TESTNAME=test_integration.DrillTest
deps =
  JPype1==1.4.1
  coverage==4.5.4
  pyarrow==15.0.0
  numpy<2
  unittest-xml-reporting
commands =
  python --version
  mkdir -p {envdir}/javalib
  mvn compile assembly:single -f arrow-jdbc-extension/pom.xml
  bash -c 'cp {tox_root}/arrow-jdbc-extension/target/arrow-jdbc*.jar {tox_root}/jaydebeapiarrow/lib'
  driver-hsqldb: bash ci/mvnget.sh org.hsqldb:hsqldb:2.7.2 {envdir}/javalib/
  driver-sqliteXerial: bash ci/mvnget.sh org.xerial:sqlite-jdbc:3.36.0 {envdir}/javalib/
  driver-postgres: bash ci/mvnget.sh org.postgresql:postgresql:42.7.2 {envdir}/javalib/
  driver-mysql: bash ci/mvnget.sh com.mysql:mysql-connector-j:8.3.0 {envdir}/javalib/
  driver-mssql: bash ci/mvnget.sh com.microsoft.sqlserver:mssql-jdbc:12.6.1.jre11 {envdir}/javalib/
  driver-trino: bash ci/mvnget.sh io.trino:trino-jdbc:461 {envdir}/javalib/
  driver-oracle: bash ci/mvnget.sh com.oracle.database.jdbc:ojdbc11:23.5.0.24.07 {envdir}/javalib/
  driver-db2: bash ci/mvnget.sh com.ibm.db2:jcc:11.5.9.0 {envdir}/javalib/
  driver-drill: bash ci/mvnget.sh org.apache.drill.exec:drill-jdbc-all:1.21.0 {envdir}/javalib/
  driver-mock: mvn compile assembly:single -f mockdriver/pom.xml
  driver-mock: bash -c 'cp {tox_root}/mockdriver/target/mockdriver*.jar {envdir}/javalib/'
;  {posargs:coverage run -a --source jaydebeapi test/testsuite.py {env:TESTNAME}}
  python test/testsuite.py -x -s {envname} {env:TESTNAME}
